#!/bin/sh

clear

figlet SMB
figlet SECURITY
figlet MODE
echo ""

echo -n "\033[0;36m[*] Target Url : "
read a
if [ ! -z $a ]
then
echo "[*] Scanning... "
nmap -p445 script smb-security-mode $a
else
echo "\033[31m[!] please Enter target  Url! "
fi
