#!/bin/sh

clear

figlet  SMB
figlet  ENUM
figlet  SESSIONS
echo ""

echo -n "\033[0;36m[*] Target Url : "
read p
if [ ! -z $p ]
then
echo "[*] Scanning... "
nmap -p 445 --script smb-enum-sessions $p
else
echo "\033[31m[!] please Enter target  Url !"
fi
